# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'singleSignInFB' do
  pod 'Firebase/Auth'
  pod 'FBSDKCoreKit'  
  pod 'FBSDKLoginKit'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for singleSignInFB

end
