# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheSocialLogin' do
  pod 'Firebase/Core' 
  pod 'Firebase' 
  pod 'FirebaseAuth' 
  pod 'FirebaseDatabase' 
  pod 'Firebase/Database' 
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit' 
  pod 'FBSDKLoginKit' 
  pod 'TwitterKit'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheSocialLogin

end
